### ISSUE TITLE
Debian 10 : python-gpgme is obsolete

### ISSUE THREAD

**Issue by hardware** [infertux/zeyple#60] opened 2019-08-10 13:15 UTC
Hi,

python-gpgme is no longer supported by upstream for about four years and has a successor (python-pgp and python3-gpg). 

> pygpgme (PyGPGME on PyPi) was started by James Henstridge. Beside Python2 it supports Python 3 since v0.3 (March 2012). The wrapping is done using python's C interface directly without using a generator tool like SWIG. This project has not been updated since 2013 and should probably be considered obsolete.

Source : https://wiki.python.org/moin/GnuPrivacyGuard

I'm going to upgrade https://github.com/hardware/mailserver to Debian 10 "Buster", but python-gpgme does not exist anymore in Debian official repos.

I can look to upgrade Zeyple but I'm not familiar with Zeyple codebase.

Best Regards.

**Comment by infertux** [comment] 2019-08-31 06:05
Hi, this is a duplicate of https://github.com/infertux/zeyple/issues/52. Sadly I don't have much time to work on Zeyple these days but if you want to update `zeyple.py` to use the new `python-gpg` package, I'd be happy to merge the PR. I'm going to close this issue, let's continue the conversation at https://github.com/infertux/zeyple/issues/52.

**Closed by infertux** 2019-08-31 06:05 UTC
